kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: bschmeli-cnes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
